# Generated by Django 2.2.16 on 2023-03-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230331_1613'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow',
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
